import React from 'react'
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
import styled from '@emotion/styled'
import { withRouter } from 'next/router';

function Blog() {
    

    const blogText = [
        { id: 1, text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in metus posuere, vehicula sapien sed, egestas turpis. Phasellus blandit lobortis massa, ac porttitor felis consequat vitae. Sed dui felis, lacinia ut elit ac, molestie euismod enim. Nulla non ante in augue molestie rutrum aliquam at dui. Integer nulla ipsum, condimentum at mollis nec, feugiat ut est. Quisque feugiat, ante ac consectetur sollicitudin, elit velit venenatis turpis, et ullamcorper tortor justo et lorem. Etiam justo odio, iaculis ac efficitur sit amet, pellentesque eu eros. Curabitur sagittis eget felis id feugiat. Nulla facilisi. Integer ut ligula vitae neque cursus maximus. Fusce eu ligula commodo, accumsan velit sed, fringilla ipsum. Mauris faucibus purus et sapien laoreet pretium. Ut nibh mauris, pretium ut lacinia at, accumsan et risus. Nam eu leo viverra odio finibus convallis et nec metus. Curabitur id ultrices magna, id placerat mi. Donec quis posuere libero. Vivamus eu vestibulum elit. Nullam eu mattis arcu. Duis aliquam pellentesque vulputate. Praesent a justo rutrum, mattis nibh vitae, congue tellus. Proin lobortis odio ut ante cursus pharetra nec quis sapien. In nec velit diam. Pellentesque accumsan turpis magna, eget pharetra diam blandit at. Nulla posuere, dui faucibus feugiat luctus, erat ex efficitur ante, sit amet facilisis orci quam ac mauris. Maecenas a maximus orci. Vestibulum ante sapien, pretium vitae tincidunt at, bibendum non ante. Etiam et sem non ipsum elementum euismod ac sollicitudin ipsum. Vivamus porta iaculis turpis quis ultricies. Nam hendrerit, arcu ac rutrum accumsan, leo mi pretium nisl, quis blandit erat orci eu sem. Aliquam pellentesque metus nulla, ac feugiat quam consequat sit amet. Nunc nec quam malesuada, finibus sapien ac, rhoncus elit. Quisque dignissim magna risus, eu tristique mauris accumsan non. Nullam ut viverra sapien. Aenean vel nisi tristique, malesuada magna vel, volutpat arcu. Duis magna urna, egestas quis dapibus nec, hendrerit sit amet libero. Nam ut iaculis nulla, vel molestie nisi. Nunc in feugiat nulla, sed mollis ligula. Praesent vitae orci scelerisque, sagittis massa at, faucibus odio. Maecenas vitae varius dolor, at accumsan massa."},
        { id: 2, text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in metus posuere, vehicula sapien sed, egestas turpis. Phasellus blandit lobortis massa, ac porttitor felis consequat vitae. Sed dui felis, lacinia ut elit ac, molestie euismod enim. Nulla non ante in augue molestie rutrum aliquam at dui. Integer nulla ipsum, condimentum at mollis nec, feugiat ut est. Quisque feugiat, ante ac consectetur sollicitudin, elit velit venenatis turpis, et ullamcorper tortor justo et lorem. Etiam justo odio, iaculis ac efficitur sit amet, pellentesque eu eros. Curabitur sagittis eget felis id feugiat. Nulla facilisi. Integer ut ligula vitae neque cursus maximus. Fusce eu ligula commodo, accumsan velit sed, fringilla ipsum. Mauris faucibus purus et sapien laoreet pretium. Ut nibh mauris, pretium ut lacinia at, accumsan et risus. Nam eu leo viverra odio finibus convallis et nec metus. Curabitur id ultrices magna, id placerat mi. Donec quis posuere libero. Vivamus eu vestibulum elit. Nullam eu mattis arcu. Duis aliquam pellentesque vulputate. Praesent a justo rutrum, mattis nibh vitae, congue tellus. Proin lobortis odio ut ante cursus pharetra nec quis sapien. In nec velit diam. Pellentesque accumsan turpis magna, eget pharetra diam blandit at. Nulla posuere, dui faucibus feugiat luctus, erat ex efficitur ante, sit amet facilisis orci quam ac mauris. Maecenas a maximus orci. Vestibulum ante sapien, pretium vitae tincidunt at, bibendum non ante. Etiam et sem non ipsum elementum euismod ac sollicitudin ipsum. Vivamus porta iaculis turpis quis ultricies. Nam hendrerit, arcu ac rutrum accumsan, leo mi pretium nisl, quis blandit erat orci eu sem. Aliquam pellentesque metus nulla, ac feugiat quam consequat sit amet. Nunc nec quam malesuada, finibus sapien ac, rhoncus elit. Quisque dignissim magna risus, eu tristique mauris accumsan non. Nullam ut viverra sapien. Aenean vel nisi tristique, malesuada magna vel, volutpat arcu. Duis magna urna, egestas quis dapibus nec, hendrerit sit amet libero. Nam ut iaculis nulla, vel molestie nisi. Nunc in feugiat nulla, sed mollis ligula. Praesent vitae orci scelerisque, sagittis massa at, faucibus odio. Maecenas vitae varius dolor, at accumsan massa."},
        { id: 3, text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in metus posuere, vehicula sapien sed, egestas turpis. Phasellus blandit lobortis massa, ac porttitor felis consequat vitae. Sed dui felis, lacinia ut elit ac, molestie euismod enim. Nulla non ante in augue molestie rutrum aliquam at dui. Integer nulla ipsum, condimentum at mollis nec, feugiat ut est. Quisque feugiat, ante ac consectetur sollicitudin, elit velit venenatis turpis, et ullamcorper tortor justo et lorem. Etiam justo odio, iaculis ac efficitur sit amet, pellentesque eu eros. Curabitur sagittis eget felis id feugiat. Nulla facilisi. Integer ut ligula vitae neque cursus maximus. Fusce eu ligula commodo, accumsan velit sed, fringilla ipsum. Mauris faucibus purus et sapien laoreet pretium. Ut nibh mauris, pretium ut lacinia at, accumsan et risus. Nam eu leo viverra odio finibus convallis et nec metus. Curabitur id ultrices magna, id placerat mi. Donec quis posuere libero. Vivamus eu vestibulum elit. Nullam eu mattis arcu. Duis aliquam pellentesque vulputate. Praesent a justo rutrum, mattis nibh vitae, congue tellus. Proin lobortis odio ut ante cursus pharetra nec quis sapien. In nec velit diam. Pellentesque accumsan turpis magna, eget pharetra diam blandit at. Nulla posuere, dui faucibus feugiat luctus, erat ex efficitur ante, sit amet facilisis orci quam ac mauris. Maecenas a maximus orci. Vestibulum ante sapien, pretium vitae tincidunt at, bibendum non ante. Etiam et sem non ipsum elementum euismod ac sollicitudin ipsum. Vivamus porta iaculis turpis quis ultricies. Nam hendrerit, arcu ac rutrum accumsan, leo mi pretium nisl, quis blandit erat orci eu sem. Aliquam pellentesque metus nulla, ac feugiat quam consequat sit amet. Nunc nec quam malesuada, finibus sapien ac, rhoncus elit. Quisque dignissim magna risus, eu tristique mauris accumsan non. Nullam ut viverra sapien. Aenean vel nisi tristique, malesuada magna vel, volutpat arcu. Duis magna urna, egestas quis dapibus nec, hendrerit sit amet libero. Nam ut iaculis nulla, vel molestie nisi. Nunc in feugiat nulla, sed mollis ligula. Praesent vitae orci scelerisque, sagittis massa at, faucibus odio. Maecenas vitae varius dolor, at accumsan massa."},
      ]
    
    return (
        <div>
            <h1>Blog</h1>
        </div>
    )
}

export default Blog;